In [5]:
using LinearAlgebra
using LinearAlgebra: mul!, Adjoint


#### Adjoint

In [12]:
X = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [20]:
Adjoint(X) 

3×2 Adjoint{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [23]:
X'

3×2 Adjoint{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

In [25]:
X2 = permutedims(X)

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [31]:
X2[:,1]

3-element Array{Int64,1}:
 1
 2
 3

In [4]:
??Adjoint

search: Adjoint adjoint adjoint!



```
Adjoint
```

Lazy wrapper type for an adjoint view of the underlying linear algebra object, usually an `AbstractVector`/`AbstractMatrix`, but also some `Factorization`, for instance. Usually, the `Adjoint` constructor should not be called directly, use [`adjoint`](@ref) instead. To materialize the view use [`copy`](@ref).

This type is intended for linear algebra usage - for general data manipulation see [`permutedims`](@ref Base.permutedims).

# Examples

```jldoctest
julia> A = [3+2im 9+2im; 8+7im  4+6im]
2×2 Array{Complex{Int64},2}:
 3+2im  9+2im
 8+7im  4+6im

julia> adjoint(A)
2×2 Adjoint{Complex{Int64},Array{Complex{Int64},2}}:
 3-2im  8-7im
 9-2im  4-6im
```
